sudo: required

language: node_js

services:
  - docker

install: true

after_success:
  - docker build -t mpawlik/hyperflow .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mpawlik/hyperflow
